# Generated by Django 5.2.4 on 2025-07-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_post_options_postcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="poster_image",
            field=models.ImageField(
                default="posts/post-default.png", upload_to="posts/"
            ),
        ),
    ]
